### ISSUE TITLE
Software set up during experiment checklist

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#281]
Paulo, Valeria, and I ran Minecraft with ToMCAT agent with successes. However, the process of preparing the ToMCAT agent for missions requires a lot of monitoring and validation steps. We need a full checklist for setting up the experiments to ensure that the experiments go smoothly and quickly.

For example, we need to ensure that speechAnalyzer detects speech connection from each of the ClientMap by using Dozzle (Logger) before launching the mission. If it does not detect the ClientMap speech connection, then we much toggle the speaker button on the ClientMap to request re-connection.

**Comment by eduongAZ** [comment]
```
version: '3'

networks:
  asist_net:
   external: true    
    
services:
  uaz_tmm_agent:
    image: gitlab.asist.aptima.com:5050/asist/testbed/uaz_tmm_agent:3.5.2
    container_name: ASI_UAZ_TA1_ToMCAT
    volumes:
      - ./logs:/tomcat-tmm/data/asist/study3_intervention1/logs
    networks:
      asist_net:
        aliases:
          - uaz_tmm_agent
    entrypoint: ["bash", "entrypoint.sh"]
  heartbeat:
    image: gitlab.asist.aptima.com:5050/asist/testbed/heartbeat:1.0.0
    container_name: heartbeat-ASI_UAZ_TA1_ToMCAT
    volumes:
      - ${HOST_DIRECTORY}config.json:/heartbeat/config.json
    networks:
      asist_net:
        aliases:
          - heartbeat-uaz_tmm_agent
    entrypoint: ["python3", "heartbeat.py"]
```
