### ISSUE TITLE
ToMCAT agent does not output logs when launched through testbed MalmoControl dashboard

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat#282]
Currently, the only way to make the agent outputs the log file is by launching it manually using docker-compose command. However, we would like the agent to also output the log file when it is launched through the MalmoControl dashboard for debugging purposes.

**Comment by vincentraymond-ua** [comment]
I've briefly looked into this, but didn't make much headway. I thought maybe the MalmoControl dashboard could be calling the docker-compose.yml file from a different directory, causing the logs directory to be mounted elsewhere. However, after some research I discovered that even if this is the case, the logs directory would still always be mounted under testbed/Agents/ASI_UAZ_TA1_ToMCAT

Launching the agent manually without the dashboard could cause issues down the line, as the Testbed now has a filter to prevent unauthorized intervention messages from displaying in Minecraft. However, in our testing last week, we were able to see the messages, even when launched manually for some reason.

**Comment by eduongAZ** [comment]
```
version: '3'

networks:
  asist_net:
   external: true    
    
services:
  uaz_tmm_agent:
    image: gitlab.asist.aptima.com:5050/asist/testbed/uaz_tmm_agent:3.5.2
    container_name: ASI_UAZ_TA1_ToMCAT
    volumes:
      - ./logs:/tomcat-tmm/data/asist/study3_intervention1/logs
    networks:
      asist_net:
        aliases:
          - uaz_tmm_agent
    entrypoint: ["bash", "entrypoint.sh"]
  heartbeat:
    image: gitlab.asist.aptima.com:5050/asist/testbed/heartbeat:1.0.0
    container_name: heartbeat-ASI_UAZ_TA1_ToMCAT
    volumes:
      - ${HOST_DIRECTORY}config.json:/heartbeat/config.json
    networks:
      asist_net:
        aliases:
          - heartbeat-uaz_tmm_agent
    entrypoint: ["python3", "heartbeat.py"]
```
